spring:
  application:
    name: api-gateway
server:
  port: 8050
eureka:
  instance:
    hostname: gateway
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
zuul:
  routes:
    account:
      path: /user/**
      service-id: user-service
    test:
      path: /message/**
      service-id: message-service